### ISSUE TITLE
Non-existant addresses have high risk

### ISSUE THREAD

**Issue by fulldecent** [PerinnoAB/DirtyHash#12]
Example https://dirtyhash.com/search/0xd91748d9c193b4b91687fe6e20e57b0bd7329595

I tested this input by fuzzing

![Uploading Screen Shot 2022-10-04 at 23.23.13.png…]()

**Comment by amiacs** [comment]
Thanks for reporting this bug!

**Comment by amiacs** [comment]
This bug is fixed now. New ETH addresses will be shown as 'Unknown'.
