### ISSUE TITLE
Tornado cash has 0% risk

### ISSUE THREAD

**Issue by fulldecent** [PerinnoAB/DirtyHash#13]
0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc

<img width="1367" alt="Screen Shot 2022-10-04 at 23 29 07" src="https://user-images.githubusercontent.com/382183/193975367-9a8a5461-f20f-4e4f-8b91-046b36daac3c.png">

**Comment by amiacs** [comment]
Fixed.
