### ISSUE TITLE
Clearly separate reasoning from factual basis

### ISSUE THREAD

**Issue by fulldecent** [PerinnoAB/DirtyHash#9]
The report could better separate the conclusions section from the factual basis.

---

For example, a template could be used for the conclusion section:

SCORE: XXX%

CAVEAT: DirtyHash makes this assessment based on the information below.

EXPLANATION: This is influenced mostly by REASON 1 and REASON 2.

---

And a template could be used for each information section. This will allow others to independently verify each piece of information and also to apply their own analysis of the data to make their own decisions.

For example EVERY input could use this same format:

NAME / DESCRIPTION: Number and timing of transactions

DATA: 738 transactions were recorded over Ethereum Mainnet and Polygon, also the timing of each transaction was considered

SOURCE: Collected as of 2022-10-03 20:33Z using our private indexing node. You can access this data publicly on Etherscan (LINK)

LIMITATIONS: Our node only checks Ethereum-format addresses on Ethereum Mainnet, Polygon and Optimism networks. 

RELIABLIITY: Addresses with over 1,000 transactions may fail to be collected properly at this time.

---

See also:

- Experian reporting format
- Reporting format used by FBI field agents do describe sourcing of information

**Comment by amiacs** [comment]
Thanks for the feedback!

**Comment by amiacs** [comment]
Re-organized the UI layout to address the above comments. Thx!
